name: cost_calculator_app
description: Coin Cost Calculator


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  #UI Utility
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3

  #State Management
  provider: ^6.0.2

  #Core Utility
  flutter_form_bloc: ^0.30.1

  #Animation
  animations: ^2.0.2
  lottie: ^1.3.0

  #Local Storage
  hive: ^2.1.0
  hive_flutter: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  build_runner: ^2.1.8

  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: MontSerrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300  